/*
 * NiFi Rest API
 *
 * The Rest API provides programmatic access to command and control a NiFi instance in real time. Start and                                             stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * The version of the OpenAPI document: 1.16.0
 * Contact: dev@nifi.apache.org
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct JvmDiagnosticsSnapshotDto {
    #[serde(rename = "systemDiagnosticsDto", skip_serializing_if = "Option::is_none")]
    pub system_diagnostics_dto: Option<Box<crate::models::JvmSystemDiagnosticsSnapshotDto>>,
    #[serde(rename = "flowDiagnosticsDto", skip_serializing_if = "Option::is_none")]
    pub flow_diagnostics_dto: Option<Box<crate::models::JvmFlowDiagnosticsSnapshotDto>>,
    #[serde(rename = "controllerDiagnostics", skip_serializing_if = "Option::is_none")]
    pub controller_diagnostics: Option<Box<crate::models::JvmControllerDiagnosticsSnapshotDto>>,
}

impl JvmDiagnosticsSnapshotDto {
    pub fn new() -> JvmDiagnosticsSnapshotDto {
        JvmDiagnosticsSnapshotDto {
            system_diagnostics_dto: None,
            flow_diagnostics_dto: None,
            controller_diagnostics: None,
        }
    }
}


