/*
 * NiFi Rest API
 *
 * The Rest API provides programmatic access to command and control a NiFi instance in real time. Start and                                             stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * The version of the OpenAPI document: 1.16.0
 * Contact: dev@nifi.apache.org
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ParameterContextDto {
    /// The Name of the Parameter Context.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The Description of the Parameter Context.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The Parameters for the Parameter Context
    #[serde(rename = "parameters", skip_serializing_if = "Option::is_none")]
    pub parameters: Option<Vec<crate::models::ParameterEntity>>,
    /// The Process Groups that are bound to this Parameter Context
    #[serde(rename = "boundProcessGroups", skip_serializing_if = "Option::is_none")]
    pub bound_process_groups: Option<Vec<crate::models::ProcessGroupEntity>>,
    /// A list of references of Parameter Contexts from which this one inherits parameters
    #[serde(rename = "inheritedParameterContexts", skip_serializing_if = "Option::is_none")]
    pub inherited_parameter_contexts: Option<Vec<crate::models::ParameterContextReferenceEntity>>,
    /// The ID the Parameter Context.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
}

impl ParameterContextDto {
    pub fn new() -> ParameterContextDto {
        ParameterContextDto {
            name: None,
            description: None,
            parameters: None,
            bound_process_groups: None,
            inherited_parameter_contexts: None,
            id: None,
        }
    }
}


