/*
 * NiFi Rest API
 *
 * The Rest API provides programmatic access to command and control a NiFi instance in real time. Start and                                             stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * The version of the OpenAPI document: 1.16.0
 * Contact: dev@nifi.apache.org
 * Generated by: https://openapi-generator.tech
 */

/// Position : The position of a component on the graph



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Position {
    /// The x coordinate.
    #[serde(rename = "x", skip_serializing_if = "Option::is_none")]
    pub x: Option<f64>,
    /// The y coordinate.
    #[serde(rename = "y", skip_serializing_if = "Option::is_none")]
    pub y: Option<f64>,
}

impl Position {
    /// The position of a component on the graph
    pub fn new() -> Position {
        Position {
            x: None,
            y: None,
        }
    }
}


