/*
 * NiFi Rest API
 *
 * The Rest API provides programmatic access to command and control a NiFi instance in real time. Start and                                             stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * The version of the OpenAPI document: 1.16.0
 * Contact: dev@nifi.apache.org
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RemoteProcessGroupContentsDto {
    /// The input ports to which data can be sent.
    #[serde(rename = "inputPorts", skip_serializing_if = "Option::is_none")]
    pub input_ports: Option<Vec<crate::models::RemoteProcessGroupPortDto>>,
    /// The output ports from which data can be retrieved.
    #[serde(rename = "outputPorts", skip_serializing_if = "Option::is_none")]
    pub output_ports: Option<Vec<crate::models::RemoteProcessGroupPortDto>>,
}

impl RemoteProcessGroupContentsDto {
    pub fn new() -> RemoteProcessGroupContentsDto {
        RemoteProcessGroupContentsDto {
            input_ports: None,
            output_ports: None,
        }
    }
}


