/*
 * NiFi Rest API
 *
 * The Rest API provides programmatic access to command and control a NiFi instance in real time. Start and                                             stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * The version of the OpenAPI document: 1.16.0
 * Contact: dev@nifi.apache.org
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct StatusSnapshotDto {
    /// The timestamp of the snapshot.
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<String>,
    /// The status metrics.
    #[serde(rename = "statusMetrics", skip_serializing_if = "Option::is_none")]
    pub status_metrics: Option<::std::collections::HashMap<String, i64>>,
}

impl StatusSnapshotDto {
    pub fn new() -> StatusSnapshotDto {
        StatusSnapshotDto {
            timestamp: None,
            status_metrics: None,
        }
    }
}


